export const PLAYLISTS_LOADING = "PLAYLISTS_LOADING"
export const PLAYLISTS_LOADED = "PLAYLISTS_LOADED"
export const PLAYLISTS_LOAD_ERROR = "PLAYLISTS_LOAD_ERROR"

export const CURRENT_PLAYLIST_LOADING = "CURRENT_PLAYLIST_LOADING"
export const CURRENT_PLAYLIST_LOADED = "CURRENT_PLAYLIST_LOADED"
export const CURRENT_PLAYLIST_LOAD_ERROR = "CURRENT_PLAYLIST_LOAD_ERROR"

export const SUBSCRIBE_MODAL_OPENED = "SUBSCRIBE_MODAL_OPENED"
export const SUBSCRIBE_MODAL_CLOSED = "SUBSCRIBE_MODAL_CLOSED"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const ADMIN_AUTH_LOADING = "ADMIN_AUTH_LOADING"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE"
/*export const ADMIN_DETAILS_LOADING = "ADMIN_DETAILS_LOADING"
export const ADMIN_DETAILS_LOADED = "ÄDMIN_DETAILS_LOADED"*/

export const CREATE_PLAYLIST_LOADING = "CREATE_PLAYLIST_LOADING"
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS"
export const CREATE_PLAYLIST_FAILURE = "CREATE_PLAYLIST_FAILURE"

export const ADD_MUSIC_LOADING = "ADD_MUSIC_LOADING"
export const ADD_MUSIC_SUCCESS = "ADD_MUSIC_SUCCESS"
export const ADD_MUSIC_FAILURE = "ADD_MUSIC_FAILURE"

export const GET_USERS_LOADING = "GET_USERS_LOADING"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

export const LOGOUT_ADMIN = "LOGOUT_ADMIN"
export const AUTH_ERROR = "AUTH_ERROR"
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN"
export const CLEAR_REDIRECT_TO_LOGIN = "CLEAR_REDIRECT_TO_LOGIN"

